name: lost_found_pet_prototype
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  line_icons: ^0.2.0
  modal_progress_hud: ^0.1.3
  datetime_picker_formfield: ^0.4.0
  flushbar: ^1.8.0
  multi_image_picker: ^4.3.6
  flutter_swiper: ^1.1.6
  incrementally_loading_listview: ^0.2.0

  provider: ^3.0.0+1
  get_it: ^1.0.3+2
  http: ^0.12.0+2
  email_validator: ^1.0.0
  json_annotation: ^2.4.0
  timeago: ^2.0.18

  firebase_core: ^0.4.0+6
  cloud_firestore: ^0.12.7
  firebase_auth: ^0.11.1+7
  firebase_storage: ^3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  json_serializable: ^3.0.0


flutter:
  uses-material-design: true

  assets:
    - images/
    - images/pattern/

  fonts:
    - family: JosefinSans
      fonts:
        - asset: fonts/JosefinSans-Regular.ttf
        - asset: fonts/JosefinSans-SemiBold.ttf
          weight: 600
        - asset: fonts/JosefinSans-Bold.ttf
          weight: 700
